---
title: "DC-2017-01-09-506cb"
output: html_document
runtime: shiny_prerendered
---

```{r include=FALSE}
library(tutor)
library(checkr)
knitr::opts_chunk$set(exercise.checker = checkr::checkr_tutor)
```

```{r DC-2017-01-09-506cb-setup, echo = FALSE}
library(DataComputing)
library(ggplot2)
```

The commands in the code pane are a non-working attempt to create a scatterplot of `death` rate versus `life` expectancy in the `CountryData` data table. Fix it.

```{r DC-2017-01-09-506cb, exercise = TRUE, exercise.setup = "DC-2017-01-09-506cb-setup", exercise.eval = FALSE, warning = FALSE, out.width = "50%", message=FALSE}
CountryData %>%
  ggplot(x = life, y = death) + 
  geom_point()
```

<div id='DC-2017-01-09-506cb-hint'>
Almost everything is correct in the command as given: the name of the data table, the use of `geom_point()` to add a scatter-plot layer, the variable names. Just one thing is missing.
</div>

```{r DC-2017-01-09-506cb-solution, echo = FALSE}
CountryData %>%
  ggplot(aes(x = life, y = death)) + 
  geom_point()
```

```{r DC-2017-01-09-506cb-code-check, echo = FALSE}
# put pre-evaluation checking here. This can be blank, in which case
# the code will be checked by the interpreter with the usual R error messages
# shown in the even of a problem.
check_blanks(USER_CODE)
```

```{r DC-2017-01-09-506cb-check, echo = FALSE}
set_success_message("Good job!") # change as you like
test_0 <- find_pipe_start("CountryData",
                          message = "put back `CountryData` as the start of the pipe.")
test_1 <- find_call("ggplot(whatever, x = whatever, y = whatever)")
test_2 <- find_call("aes(x = whatever, y = whatever)",
                    message = "where do you map the variables to the x and y aesthetics?" )
test_3 <- find_call("whatever + whatever", 
                    message = "the two components of the plot --- the frame made by `ggplot()` and the layer made by `geom_point()` --- are connected with the `+` operator.")
test_4 <- find_call("geom_point()",
                    message = "remember to add the scatter-plot layer with `geom_point()`.")
USER_CODE %>% test_0 %>% test_1 %>% was_mistake("you still haven't fixed it.") %>% test_2 %>% test_3 %>% test_4 
```


