---
title: "DC-2017-01-02-b2a9c"
output: html_document
runtime: shiny_prerendered
---

```{r include=FALSE}
library(tutor)
library(checkr)
knitr::opts_chunk$set(exercise.checker = checkr::checkr_tutor)
```

```{r DC-2017-01-02-b2a9c-setup, echo = FALSE}
# code to be evaluated before exercise code
```

The code pane contains a statement that will read in a data table from the internet.

Add commands that use the appropriate functions to:

- Calculate the number of rows
- Calculate the number of columns
- Find the names of the variables


```{r DC-2017-01-02-b2a9c, exercise = TRUE, exercise.setup = "DC-2017-01-02-b2a9c-setup", exercise.eval = FALSE}
Motors <- read.csv("http://tiny.cc/mosaic/engines.csv")

____(____)   # number of rows in Motors
____(____)   # number of columns in Motors
____(____)   # names of  variables in Motors
```

<div id="DC-2017-01-02-b2a9c-hint">
The functions are `nrow()`, `ncol()`, and `names()`. Each of them takes as an argument the data table.
</div>

```{r DC-2017-01-02-b2a9c-solution, echo = FALSE}
Motors <- read.csv("http://tiny.cc/mosaic/engines.csv")

nrow(Motors)
ncol(Motors)
names(Motors)
```

```{r DC-2017-01-02-b2a9c-check, echo = FALSE}
set_success_message("Good. These are simple ways to see basic properties of a data table.")
test_0 <- find_call("nrow()")
test_1 <- find_call("nrow(whatever)", "Use `nrow()` to find the number of rows in a data table.")
test_1a <- check_argument("nrow(grab_this)", test = agrees(is.data.frame(x)))
test_2 <- find_call("names(whatever)", "`names()` finds the names of the variables in a data table.")
test_2a <- check_argument("names(grab_this)", test = agrees(is.data.frame(x)))
test_3 <- find_call("ncol(whatever)", "Use `ncol()` to find the number of columns in a data table.")
test_3a <- check_argument("ncols(grab_this)", test = agrees(is.data.frame(x)))
USER_CODE %>% 
#  test_0 %>% was_mistake(message = "give the data table as the argument to nrow().") %>%
  test_1 %>% test_1a %>%
  test_2 %>% test_2a %>%
  test_3 # %>% test_3a
```


